### ISSUE TITLE
[Resonite] The "SYNC METHODS HERE" expander button should not be generated if there would be no delegates put inside based on the current mod config

### ISSUE THREAD

**Issue by Nytra** [art0007i/ShowDelegates#5]
For example Grabbable component doesn't have any delegates shown in vanilla, however if you choose the config option to show only vanilla delegates the mod still generates the expander even though it will be empty.

**Comment by art0007i** [comment]
also you don't have to put [resonite]. the neos one is now deprecated and if anyone wants to work on it they can make a fork. this applies to all my mods that I've ported
