### ISSUE TITLE
Broken in new settings pre-release

### ISSUE THREAD

**Issue by Nytra** [art0007i/ShowDelegates#8]
Prevents inspector UI from generating

[DESKTOP-H976HO2 - 2024.4.3.1385 - 2024-04-04 02_07_04.log](https://github.com/art0007i/ShowDelegates/files/14860108/DESKTOP-H976HO2.-.2024.4.3.1385.-.2024-04-04.02_07_04.log)

**Comment by art0007i** [comment]
fixed in latest release
